Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 30
AllCops:
  Exclude:
    - 'Guardfile'
