Style/ClassAndModuleChildren:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 40
Metrics/AbcSize:
  Max: 40
AllCops:
  Exclude:
    - 'Guardfile'
